   
install.packages("tidyverse")
install.packages("caTools")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
install.packages("philentropy")
install.packages("ggplot2")
install.packages("RColorBrewer")
install.packages("stats")
install.packages("dplyr")
install.packages("ggfortify")
install.packages("dbscan")
install.packages("amap")
